controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


authentication_token:
    path: /api/authentication_token
    methods: ['POST']

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui
