api_platform:
    # The title of the API.
    title: 'API Hangover'

    # The description of the API.
    description: 'API for hangover app'

    # The version of the API.
    version: '0.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    formats:
        json:
            mime_types: [ 'application/json' ]
    enable_swagger_ui: false
    enable_re_doc: false
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
